
jsonfile='/Volumes/Buzon/DriftData/wehr5917/gap3sc/track2p/diagnostics/partial_track_summaryANCHOR_AGNOSTIC_SEEDINGTrue.json'
%same as the png generated by fix3_partial_tracks.py

ptr=jsondecode(fileread(jsonfile));

nk=length(ptr.results_by_plane.recovery_by_k)
for i=1:nk
    k(i)=ptr.results_by_plane.recovery_by_k(i).k;
    n_cells(i)=ptr.results_by_plane.recovery_by_k(i).n_cells;
end

% figure
plot(k, n_cells, '-o')
set(gca, 'xdir', 'reverse')
xlim([.9*min(k) 1.1*max(k)])
xticks(sort(k))
ylabel('# cells recovered')
xlabel ('K (min sessions present)')